config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[ new create destroy ]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "inbox_items#index"

  resources :inbox_items, only: %i[ index new edit update create ]
  resources :projects, only: %i[ index show new edit update create destroy ]

  resources :next_actions do
    collection do
      post :destroy_done
    end
  end
end

app/controllers/next_actions_controller.rb
class NextActionsController < ApplicationController
  before_action :set_next_action, only: %i[ show edit update destroy ]

  # GET /next_actions or /next_actions.json
  def index
    @next_actions = Current.user.next_actions
  end

  # GET /next_actions/new
  def new
    @next_action = Current.user.next_actions.new
  end

  # GET /next_actions/1/edit
  def edit
  end

  # POST /next_actions or /next_actions.json
  def create
    @next_action = Current.user.next_actions.new(next_action_params)

    respond_to do |format|
      if @next_action.save
        format.html { redirect_to next_actions_path, notice: "Next action was successfully created." }
        format.json { render :show, status: :created, location: @next_action }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @next_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /next_actions/1 or /next_actions/1.json
  def update
    respond_to do |format|
      if @next_action.update(next_action_params)
        format.html { redirect_to next_actions_path, notice: "Next action was successfully updated." }
        format.json { render :show, status: :ok, location: @next_action }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @next_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /next_actions/1 or /next_actions/1.json
  def destroy
    @next_action.destroy!

    respond_to do |format|
      format.html { redirect_to next_actions_path, status: :see_other, notice: "Next action was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def destroy_done
    Current.user.next_actions.where(done: true).destroy_all
    redirect_to next_actions_path, notice: "All done next actions deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_next_action
      @next_action = NextAction.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def next_action_params
      params.expect(next_action: [ :project_id, :body, :done, :context ])
    end
end

app/helpers/next_actions_helper.rb
module NextActionsHelper
  include MarkdownHelper
end

app/views/next_actions/_form.html.erb
<%= form_with(model: next_action) do |form| %>
  <% if next_action.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(next_action.errors.count, "error") %> prohibited this next_action from being saved:</h2>
      <ul>
        <% next_action.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :project_id, style: "display: block" %>

    <select name="next_action[project_id]">
      <option value="">Choose a project</option>
      <% Current.user.projects.grouped_by_area.each do |area, projects| %>
        <optgroup label="<%= area %>">
          <% projects.each do |project| %>
            <option value="<%= project.id %>" <%= "selected" if project.id == next_action.project_id %>><%= project.name %></option>
          <% end %>
        </optgroup>
      <% end %>
    </select>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.label :context, style: "display: block" %>
    <%= form.text_field :context, list: "context-list", value: next_action.context %>

    <datalist id="context-list">
      <% Current.user.next_actions.pluck(:context).uniq.each do |context| %>
        <option value="<%= context %>"><%= context %></option>
      <% end %>
    </datalist>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/next_actions/_next_action.html.erb
<%= turbo_frame_tag next_action, class: "next-action" do %>
  <p>
    <% if next_action.done %>
      <s><%= next_action.body %></s>
    <% else %>
      <%= next_action.body %> 
    <% end %>

    <% if next_action.project.present? && !current_page?(project_path(next_action.project)) %>
      -- <%= link_to next_action.project.name, next_action.project %>
    <% end %>

    <% if next_action.context.present? && !current_page?(next_actions_path) %>
      @<%= next_action.context %>
    <% end %>
  </p>

  <div class="next-action-actions">
    <% if next_action.done %>
      <%= button_to "Not done", next_action_path(next_action), params: { next_action: { done: false } }, method: :patch %>
    <% else %>
      <%= button_to "Done", next_action_path(next_action), params: { next_action: { done: true } }, method: :patch %>
    <% end %>

    <% unless current_page?(next_action_path(next_action)) %>
      <%= link_to "Show", next_action_path(next_action), target: "_top" %>
    <% end %>

    <%= link_to "Edit", edit_next_action_path(next_action), target: "_top" %>
  </div>
<% end %>

app/views/next_actions/edit.html.erb
<% content_for :title, "Editing next action" %>

<h1>Editing next action</h1>

<%= render "form", next_action: @next_action %>

<br>

<div>
  <%= button_to "Destroy this next action", @next_action, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this next action?" } %>
  <%= link_to "Back to next actions", next_actions_path %>
</div>

app/views/next_actions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Next actions" %>

<h1>Next actions</h1>

<div id="next_actions">
  <ul>
    <% @next_actions.group_by(&:context).each do |context, next_actions| %>
      <li>
        <details open>
          <summary>
            <%= context.present? ? context : "No Context" %>
          </summary>

          <ul>
            <% next_actions.each do |next_action| %>
              <li><%= render next_action %></li>
            <% end %>
          </ul>
        </details>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "New next action", new_next_action_path %>

<% if @next_actions.done.any? %>
  <%= button_to "Delete all done", destroy_done_next_actions_path, method: :post, data: { turbo_method: :post, turbo_confirm: "Are you sure?" } %>
<% end %>

app/views/next_actions/new.html.erb
<% content_for :title, "New next action" %>

<h1>New next action</h1>

<%= render "form", next_action: @next_action %>

<br>

<div>
  <%= link_to "Back to next actions", next_actions_path %>
</div>

app/views/next_actions/show.html.erb
<% content_for :title, "Next action" %>

<%= render @next_action %>

<div>
  <%= link_to "Back to all next actions", next_actions_path %>
  <%= button_to "Destroy this next action", @next_action, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this next action?" } %>
</div>