config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[ new create destroy ]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "inbox_items#index"

  resources :inbox_items, only: %i[ index new edit update create ]
  resources :projects, only: %i[ index show new edit update create destroy ]

  resources :next_actions do
    collection do
      post :destroy_done
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include Incubation

  belongs_to :user

  validates :name, presence: true

  scope :with_area, -> { where.not(area: nil).where.not(area: "") }
  scope :without_area, -> { where(area: nil).or(where(area: "")) }

  scope :grouped_by_area, -> { with_area.order("area ASC, name ASC").group_by(&:area) }

  scope :with_waiting_for, -> { where.not(waiting_for: [ nil, "" ]) }
  scope :without_waiting_for, -> { where(waiting_for: [ nil, "" ]) }

  scope :incubating, -> { where.not(stops_incubating_at: nil) }
  scope :not_incubating, -> { where(stops_incubating_at: nil) }

  scope :active, -> { without_waiting_for.not_incubating }
  scope :inactive, -> { with_waiting_for.or(incubating) }

  has_many :next_actions, dependent: :nullify

  before_validation :set_stops_incubating_at
  validate :incubating_until_is_a_date
  validate :validate_incubating_fields

  def inactive?
    Project.inactive.exists?(id)
  end

  def active?
    !inactive?
  end

  private

  def validate_incubating_fields
    if incubating_until.present? && stops_incubating_at.blank?
      errors.add(:stops_incubating_at, "must be present if incubating_until is present")
    elsif stops_incubating_at.present? && incubating_until.blank?
      errors.add(:incubating_until, "must be present if stops_incubating_at is present")
    end
  end

  def incubating_until_is_a_date
    if incubating_until.present? && Chronic.parse(incubating_until).blank?
      errors.add(:incubating_until, "must be a valid date")
    end
  end

  def set_stops_incubating_at
    self.stops_incubating_at = Chronic.parse(incubating_until) if incubating_until.present?
    self.stops_incubating_at = nil if incubating_until.blank?
  end
end

app/models/project/incubation.rb
class Project
  module Incubation
    extend ActiveSupport::Concern

    class_methods do
      def requiring_unincubation
        where("stops_incubating_at < ?", Time.current)
      end
    end

    def unincubate
      update!(stops_incubating_at: nil, incubating_until: nil)
      user.inbox_items.create!(
        body: "Project #{name} is no longer incubating. <a href=\"/projects/#{id}\">View project</a>."
      )
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include Authentication
  before_action :set_projects
  before_action :set_project, only: %i[ show edit update destroy ]

  layout "projects"

  def index
    project = Current.user.projects.active.first

    if project
      redirect_to project_path(project)
    else
      redirect_to new_project_path
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Current.user.projects.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Current.user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_projects
      @projects = Current.user.projects
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.expect(project: [ :name, :body, :area, :waiting_for, :incubating_until ])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  include MarkdownHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :area, style: "display: block" %>
    <%= form.text_field :area, list: "areas", autocomplete: "off" %>

    <datalist id="areas">
      <% @projects.map(&:area).uniq.compact.each do |area| %>
        <option value="<%= area %>"></option>
      <% end %>
    </datalist>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.label :waiting_for, style: "display: block" %>
    <%= form.text_field :waiting_for %>
  </div>

  <div>
    <%= form.label :incubating_until, style: "display: block" %>
    <%= form.text_field :incubating_until %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<li>
  <% if local_assigns[:with_area] %>
    (<%= project.area %>)
  <% end %>

  <%= link_to project.name, project_path(project) %>

  <% if project.active? %>
    <% if project.next_actions.none? %>
      -- No next actions
    <% end %>
  <% end %>

  <% if project.waiting_for.present? %>
    -- Waiting for <%= project.waiting_for %>
  <% end %>

  <% if project.stops_incubating_at.present? %>
    -- Incubating until <%= project.stops_incubating_at.strftime("%A, %B %d %Y") %>
  <% end %>
</li>

app/views/projects/_sidebar.html.erb
<ul>
  <%= render @projects.active.without_area %>

  <% @projects.active.grouped_by_area.each do |area, projects| %>
    <li>
      <details open>
        <summary><%= area %></summary>

        <ul>
          <%= render projects %>
        </ul>
      </details>
    </li>
  <% end %>

  <li class="new-project">
    <%= link_to "New Project", new_project_path %>
  </li>

  <% if @projects.inactive.any? %>
    <li>
      <details <%= "open" if @project&.inactive? %>>
        <summary>Inactive (<%= @projects.inactive.count %>)</summary>

        <ul>
          <%= render @projects.inactive.sort_by(&:area), with_area: true %>
        </ul>
      </details>
    </li>
  <% end %>
</ul>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %>
  <%= button_to "Destroy this project", @project, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this project?" } %>
</div>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="<%= dom_id @project %>">
  <p>
    <strong>Name:</strong>
    <%= @project.name %>
  </p>

  <p>
    <strong>Body:</strong>
    <%== render_markdown(@project.body) %>
  </p>

  <p>
    <strong>Waiting for:</strong>
    <%= @project.waiting_for %>
  </p>

  <p>
    <strong>Stops incubating at:</strong>

    <% if @project.stops_incubating_at.present? %>
      <time datetime="<%= @project.stops_incubating_at %>">
        <%= @project.stops_incubating_at.strftime("%A, %B %d %Y") %>
        (<%= @project.stops_incubating_at.future? ? "in #{distance_of_time_in_words_to_now(@project.stops_incubating_at)}" : "#{distance_of_time_in_words_to_now(@project.stops_incubating_at)} ago" %>)
      </time>
    <% end %>
  </p>

  <p>
    <strong>Next actions:</strong>

    <ul>
      <% @project.next_actions.each do |next_action| %>
        <li>
          <%= render next_action %>
        </li>
      <% end %>
    </ul>
  </p>
</div>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %>
  <%= button_to "Destroy this project", @project, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this project?" } %>
</div>