config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[ new create destroy ]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "inbox_items#index"

  resources :inbox_items, only: %i[ index new edit update create ]
  resources :projects, only: %i[ index show new edit update create destroy ]

  resources :next_actions do
    collection do
      post :destroy_done
    end
  end
end

app/helpers/layouts_helper.rb
module LayoutsHelper
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(template: "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Trays" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to "Capture", new_inbox_item_path %></li>
        <li><%= link_to "Inbox", inbox_items_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to "Next Actions", next_actions_path %></li>
      </ul>
    </nav>

    <%= yield %>

    <div class="pinned-inbox-item">
      <%= render partial: "inbox_items/inbox_item", locals: { inbox_item: Current.user.pinned_inbox_item } if Current.user&.pinned_inbox_item.present? %>
    </div>
  </body>
</html>

app/views/layouts/projects.html.erb
<main class="projects-layout">
  <%= render "projects/sidebar" %>

  <main>
    <%= yield %>
  </main>
</main>

<%= parent_layout :application %>